# -*- coding: utf-8 -*-
"""detection_utils

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Si0LJBqCu85Xnoc6nydT_BGYgqY73we
"""

from IPython.core.interactiveshell import re
import numpy as np
#IOU
import torch

# ==========================================
#  METRICS & ALGORITHMS (IoU / NMS)
# ==========================================
def intersection_over_union(boxes_preds, boxes_labels, box_format="midpoint"):
  if box_format == "midpoint":
    box1_x1=boxes_preds[...,0:1]-boxes_preds[...,2:3]/2
    box1_y1=boxes_preds[...,1:2]-boxes_preds[...,3:4]/2
    box1_x2=boxes_preds[...,0:1]+boxes_preds[...,2:3]/2
    box1_y2=boxes_preds[...,1:2]+boxes_preds[...,3:4]/2
    box2_x1=boxes_labels[...,0:1]-boxes_labels[...,2:3]/2
    box2_y1=boxes_labels[...,1:2]-boxes_labels[...,3:4]/2
    box2_x2=boxes_labels[...,0:1]+boxes_labels[...,2:3]/2
    box2_y2=boxes_labels[...,1:2]+boxes_labels[...,3:4]/2

  else:
    box1_x1=boxes_preds[...,0:1]
    box1_y1=boxes_preds[...,1:2]
    box1_x2=boxes_preds[...,2:3]
    box1_y2=boxes_preds[...,3:4]
    box2_x1=boxes_labels[...,0:1]
    box2_y1=boxes_labels[...,1:2]
    box2_x2=boxes_labels[...,2:3]
    box2_y2=boxes_labels[...,3:4]

  #corner points of intersection
  x1=torch.max(box1_x1,box2_x1)
  y1=torch.max(box1_y1,box2_y1)
  x2=torch.min(box1_x2,box2_x2)
  y2=torch.min(box1_y2,box2_y2)

  #IoU=intersection area/union of both boxes (area of box1+area of box 2 - intersection = union)
  intersection=(x2-x1).clamp(0)*(y2-y1).clamp(0)

  box1_area=abs((box1_x2-box1_x1)*(box1_y2-box1_y1))
  box2_area=abs((box2_x2-box2_x1)*(box2_y2-box2_y1))

  return intersection/(box1_area+box2_area-intersection+1e-6)


# NMS
def non_max_suppression(bboxes,iou_threshold,threshold,box_format="corners"):
  assert type(bboxes)==list

  bboxes=[box for box in bboxes if box[1]>threshold]
  bboxes=sorted(bboxes,key=lambda x:x[1],reverse=True)
  bboxes_after_nms=[]

  while bboxes:
    chosen_box=bboxes[0]
    bboxes=bboxes[1:]
    bboxes_after_nms.append(chosen_box)

    bboxes = [
              box for box in bboxes
              if intersection_over_union(
                       torch.tensor(chosen_box),
                       torch.tensor(box),
                       box_format=box_format
                       ) <= iou_threshold
              ]

  return bboxes_after_nms


# ==========================================
#  LOSSES funtions(CrossEntropyLoss and MSELoss)
# ==========================================
#Cross Entropy Loss
def CrossEntropyLoss(logits, target):
    logits = np.array(logits)
    target = np.array(target)

    # Subtracting the maximum logit prevents np.exp() from overflowing to infinity
    logits_stable = logits - np.max(logits)

    exp_logits = np.exp(logits_stable)

    softmax_probs = exp_logits / np.sum(exp_logits)

    loss = -np.sum(target * np.log(softmax_probs + 1e-9))

    return loss

#MSE
def MSELoss(y_true,y_pred):
  y_true=np.array(y_true)
  y_pred=np.array(y_pred)

  return np.mean((y_true-y_pred)**2)


# ==========================================
#  BOUNDING BOX UTILS
# ==========================================
#bbox delta
def bbox_delta(ground_truth,proposals):
  #For bbox_delta (x,y,w,h) is needed we have (x1,y1,x2,y2) so converting it.
  x1,y1,x2,y2=ground_truth
  xp1,yp1,xp2,yp2=proposals

  xg=(x1+x2)/2
  yg=(y1+y2)/2
  wg=x2-x1
  hg=y2-y1

  xp=(xp1+xp2)/2
  yp=(yp1+yp2)/2
  wp=xp2-xp1
  hp=yp2-yp1

  tx=(xg-xp)/wp
  ty=(yg-yp)/hp
  tw=torch.log(wg/wp)
  th=torch.log(hg/hp)

  bbox_delta=torch.stack([tx,ty,tw,th])

  return bbox_delta


#bbox_delta_to_box
def bbox_delta_to_box(bbox_delta,proposals):
  xp1,yp1,xp2,yp2=proposals
  tx,ty,tw,th=bbox_delta

  xp=(xp1+xp2)/2
  yp=(yp1+yp2)/2
  wp=xp2-xp1
  hp=yp2-yp1

  w=wp*torch.exp(tw)
  h=hp*torch.exp(th)

  x=xp+tx*wp
  y=yp+ty*hp

  box=torch.stack([x,y,w,h])
  refined_box=torch.stack([x-w/2,y-h/2,x+w/2,y+h/2])

  return box,refined_box

