# -*- coding: utf-8 -*-
"""model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pfJFO3UHl_ktt4F8NDZgLderyJthTqdF
"""

import torch
from torch import nn
import torchvision.models as models

class RCNN(nn.Module):
  def __init__(self,num_classes=4):
    super(RCNN,self).__init__()

    resnet18 = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
    self.backbone = nn.Sequential(*list(resnet18.children())[:-1])

    for param in self.backbone.parameters():
      param.requires_grad = False
    
    #Classifier block
    self.Classifier=nn.Sequential(
                                  nn.Flatten(),

                                  nn.Linear(512,256),
                                  nn.ReLU(),
                                  nn.Dropout(0.3,inplace=False),

                                  nn.Linear(256,128),
                                  nn.ReLU(),
                                  nn.Dropout(0.3,inplace=False),

                                  nn.Linear(128,num_classes)
                                  )
    #Bbox block
    self.Bbox=nn.Sequential(
                            nn.Flatten(),

                            nn.Linear(512,256),
                            nn.ReLU(),
                            nn.Dropout(0.2),

                            nn.Linear(256,128),
                            nn.ReLU(),
                            nn.Dropout(0.2),

                            nn.Linear(128,4)
                            )
  def forward(self,x):
    features=self.backbone(x)

    class_logits=self.Classifier(features)
    bbox_deltas=self.Bbox(features)

    return class_logits,bbox_deltas

