# -*- coding: utf-8 -*-
"""detection_utils.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Si0LJBqCu85Xnoc6nydT_BGYgqY73we
"""

from IPython.core.interactiveshell import re
#IOU
import torch

def intersection_over_union(boxes_preds, boxes_labels, box_format="midpoint"):
  if box_format == "midpoint":
    box1_x1=boxes_preds[...,0:1]-boxes_preds[...,2:3]/2
    box1_y1=boxes_preds[...,1:2]-boxes_preds[...,3:4]/2
    box1_x2=boxes_preds[...,0:1]+boxes_preds[...,2:3]/2
    box1_y2=boxes_preds[...,1:2]+boxes_preds[...,3:4]/2
    box2_x1=boxes_labels[...,0:1]-boxes_labels[...,2:3]/2
    box2_y1=boxes_labels[...,1:2]-boxes_labels[...,3:4]/2
    box2_x2=boxes_labels[...,0:1]+boxes_labels[...,2:3]/2
    box2_y2=boxes_labels[...,1:2]+boxes_labels[...,3:4]/2

  else:
    box1_x1=boxes_preds[...,0:1]
    box1_y1=boxes_preds[...,1:2]
    box1_x2=boxes_preds[...,2:3]
    box1_y2=boxes_preds[...,3:4]
    box2_x1=boxes_labels[...,0:1]
    box2_y1=boxes_labels[...,1:2]
    box2_x2=boxes_labels[...,2:3]
    box2_y2=boxes_labels[...,3:4]

  #corner points of intersection
  x1=torch.max(box1_x1,box2_x1)
  y1=torch.max(box1_y1,box2_y1)
  x2=torch.min(box1_x2,box2_x2)
  y2=torch.min(box1_y2,box2_y2)

  #IoU=intersection area/union of both boxes (area of box1+area of box 2 - intersection = union)
  intersection=(x2-x1).clamp(0)*(y2-y1).clamp(0)

  box1_area=abs((box1_x2-box1_x1)*(box1_y2-box1_y1))
  box2_area=abs((box2_x2-box2_x1)*(box2_y2-box2_y1))

  return intersection/(box1_area+box2_area-intersection+1e-6)

# NMS
def non_max_suppression(bboxes,iou_threshold,threshold,box_format="corners"):
  assert type(bboxes)==list

  bboxes=[box for box in bboxes if box[1]>threshold]
  bboxes=sorted(bboxes,key=lambda x:x[1],reverse=True)
  bboxes_after_nms=[]

  while bboxes:
    chosen_box=bboxes[0]
    bboxes=bboxes[1:]
    bboxes_after_nms.append(chosen_box)

    bboxes = [
              box for box in bboxes
              if intersection_over_union(
                       torch.tensor(chosen_box),
                       torch.tensor(box),
                       box_format=box_format
                       ) <= iou_threshold
              ]

  return bboxes_after_nms

