# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iktXrlUQrzzaTsmR2R14E8FIpqYJLW6j
"""

import streamlit as st
import os
import csv
from datetime import datetime
from utils import custom_cnn_model_loader, resnet18_loader, image_transform, predict

# -----------------------------
# Streamlit App
# -----------------------------

st.title("Natural Image Classifier")
st.write("Upload an image to classify it.")

Custom_CNN = custom_cnn_model_loader()
Resnet18 = resnet18_loader()

model_choice = st.selectbox(
    options=["Resnet18", "Custom_CNN"],
    label="Select Model"
)

uploaded_file = st.file_uploader(
    "Image upload",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    st.image(
        uploaded_file,
        caption="Uploaded Image",
        use_container_width=True
    )

    transformed_img = image_transform(
        uploaded_file,
        model_choice
    )

    if model_choice == "Resnet18":
        prediction = predict(
            transformed_img,
            Resnet18
        )
    else:
        prediction = predict(
            transformed_img,
            Custom_CNN
        )

    st.success(f"Prediction: {prediction}")

